### ISSUE TITLE
Nested model not estimated

### ISSUE THREAD

**Issue by dcoynel** [pzeidman/dcm-peb-example#1]
Hi, thanks for the great tutorial.

I've followed all the steps until 3.1.5 (Diagnostics) for the estimation of the 2 models per subject. When running `spm_dcm_fmri_check(GCM)` the second column, corresponding to the _DCM_no_ldF_modulation_ models, has no data available for the variance explained for this model. 

After looking at the individual DCM files, it looks like the reduced model is not recognized as a nested model from the full model, and is consequently not estimated using the default BMR procedure. 

I'm using matlab R2019b with spm v7771 (DCM12.5). Two DCM files for sub-02 are available [here](https://drive.switch.ch/index.php/s/xCDKzAXuM5YWbPW).

Could you think of something that went wrong? I re-started the tutorial from scratch to avoid any typing mistakes.

Thanks!
David

**Comment by pzeidman** [comment]
Sorry to have missed this question! In case it's useful to others - the spm_dcm_fmri_check function can only show the explained variance for models that are fitted to the data, not "reduced" models that have their parameters / free energy derived using Bayesian model reduction.
